// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3930.whoCares.subsystems;

import org.usfirst.frc3930.whoCares.RobotMap;
import org.usfirst.frc3930.whoCares.commands.*;

import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class cameraSystem extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.
		private final Relay camera1 = RobotMap.cam1;
	    private final Relay camera2 = RobotMap.cam2;
	    private final Relay camera3 = RobotMap.cam3;
	    private final Relay camera4 = RobotMap.cam4;
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    public void camera1Activate(){
    	camera1.set(Relay.Value.kForward);
    	camera2.set(Relay.Value.kOff);
    	camera3.set(Relay.Value.kOff);
    	camera4.set(Relay.Value.kOff);

    }
    public void camera2Activate(){
    	camera1.set(Relay.Value.kOff);
    	camera2.set(Relay.Value.kForward);
    	camera3.set(Relay.Value.kOff);
    	camera4.set(Relay.Value.kOff);

    }   public void camera3Activate(){
    	camera1.set(Relay.Value.kOff);
    	camera2.set(Relay.Value.kOff);
    	camera3.set(Relay.Value.kForward);
    	camera4.set(Relay.Value.kOff);

    }   public void camera4Activate(){
    	camera1.set(Relay.Value.kOff);
    	camera2.set(Relay.Value.kOff);
    	camera3.set(Relay.Value.kOff);
    	camera4.set(Relay.Value.kForward);

    }
    
    
}

